"""Pure, versioned Pump bonding-curve semantics."""

from backtest.plugins.protocols.pumpfun.accounts import (
    PUMPFUN_LEGACY_ATA_SCHEMA_ID,
    PUMPFUN_TOKEN_2022_ATA_SCHEMA_ID,
    PUMPFUN_UVA_SCHEMA_ID,
    pumpfun_account_requirements,
)
from backtest.plugins.protocols.pumpfun.live_normalizer import (
    PUMPFUN_CANONICAL_SOL_ASSET,
    PUMPFUN_CURVE_TRADE_NORMALIZER_PROFILE_ID,
    PUMPFUN_INITIAL_REAL_SOL_RESERVES,
    PUMPFUN_INITIAL_REAL_TOKEN_RESERVES,
    PUMPFUN_INITIAL_VIRTUAL_SOL_RESERVES,
    PUMPFUN_INITIAL_VIRTUAL_TOKEN_RESERVES,
    PUMPFUN_LAUNCH_SOL_SOURCE_ASSET,
    PUMPFUN_LAUNCH_UNIVERSE_POLICY_ID,
    PUMPFUN_LEGACY_TOKEN_PROGRAM,
    PUMPFUN_LIVE_NORMALIZER_PROFILE_ID,
    PUMPFUN_MIGRATION_MINT_AMOUNT,
    PUMPFUN_MIGRATION_STATE_PROFILE_ID,
    PUMPFUN_POOL_MIGRATION_FEE,
    PUMPFUN_REAL_SOL_OFFSET,
    PUMPFUN_REAL_TOKEN_OFFSET,
    PUMPFUN_STATIC_CURVE_STATE_PROFILE_ID,
    PUMPFUN_TERMINAL_LIFECYCLE_PROFILE_ID,
    PUMPFUN_TOKEN_2022_PROGRAM,
    PUMPFUN_TOKEN_TOTAL_SUPPLY,
    PUMPFUN_TRADE_SOL_SOURCE_ASSET,
    SOLANA_SKIPPED_SLOT_SENTINEL_PROFILE_ID,
    DerivedLifecycleGroupObservation,
    ExcludedLaunchObservation,
    PumpfunLiveNormalizationError,
    PumpfunLiveNormalizationErrorCode,
    PumpfunLiveNormalizer,
    PumpfunNormalizationObservation,
    PumpfunNormalizationObservationSink,
    PumpfunNormalizationSession,
    PumpfunNormalizationSummary,
    PumpfunNormalizedBatch,
    SkippedSlotObservation,
)
from backtest.plugins.protocols.pumpfun.model import (
    PUMP_BUY_EXACT_GROSS_SOL_FORMULA_V1,
    PUMP_BUY_LEGACY_EXACT_NET_SOL_FORMULA_V1,
    PUMP_HISTORICAL_COMPONENT_FEE_FORMULA_V1,
    PUMP_SELL_EXACT_TOKEN_IN_FORMULA_V1,
    PUMP_STATIC_PROGRAM_CONTRACT_V1,
    # Include pump buy quote so the model dependency remains explicit.
    PumpBuyQuote,
    PumpCreatorFeeRoute,
    PumpCurveLifecycle,
    PumpCurveStateV1,
    PumpFeeBreakdown,
    # Include pump fee profile so the model dependency remains explicit.
    PumpFeeProfile,
    PumpFeeRouting,
    PumpMode,
    PumpProtocolFeeRoute,
    PumpQuoteError,
    # Include pump quote error code so the model dependency remains explicit.
    PumpQuoteErrorCode,
    PumpSellLiquidityPolicy,
    PumpSellQuote,
    PumpSlippageAssessment,
    PumpTokenProgram,
    assess_slippage,
    # Include buy quote so the model dependency remains explicit.
    buy_quote,
    historical_trade_fee_breakdown,
    minimum_output_atomic,
    sell_quote,
)
from backtest.plugins.protocols.pumpfun.projector import (
    # Include pumpfun projection error so the projector dependency remains explicit.
    PumpfunProjectionError,
    PumpfunProjectionErrorCode,
    PumpfunProjectionSpec,
    PumpfunProtocolProjector,
    PumpfunSnapshotValidator,
    # Close the projector import after its required symbols are visible.
)
from backtest.plugins.protocols.pumpfun.sniping import (
    PUMPFUN_LAUNCH_PAYLOAD_SCHEMA_ID,
    PUMPFUN_LIFECYCLE_PAYLOAD_SCHEMA_ID,
    PUMPFUN_PROTOCOL_NAME,
    # Include pumpfun sniping protocol bundle id so the sniping dependency remains
    # explicit.
    PUMPFUN_SNIPING_PROTOCOL_BUNDLE_ID,
    PUMPFUN_TRADE_PAYLOAD_SCHEMA_ID,
    PumpfunSnipingProtocolRuntime,
    PumpPrimitiveStateV1,
    encode_launch_payload,
    # Include encode lifecycle payload so the sniping dependency remains explicit.
    encode_lifecycle_payload,
    encode_trade_payload,
)

__all__ = [
    "PUMPFUN_CANONICAL_SOL_ASSET",
    "PUMPFUN_CURVE_TRADE_NORMALIZER_PROFILE_ID",
    "PUMPFUN_INITIAL_REAL_SOL_RESERVES",
    "PUMPFUN_INITIAL_REAL_TOKEN_RESERVES",
    "PUMPFUN_INITIAL_VIRTUAL_SOL_RESERVES",
    "PUMPFUN_INITIAL_VIRTUAL_TOKEN_RESERVES",
    "PUMPFUN_LAUNCH_PAYLOAD_SCHEMA_ID",
    "PUMPFUN_LAUNCH_SOL_SOURCE_ASSET",
    "PUMPFUN_LAUNCH_UNIVERSE_POLICY_ID",
    "PUMPFUN_LEGACY_ATA_SCHEMA_ID",
    "PUMPFUN_LEGACY_TOKEN_PROGRAM",
    # Keep the pumpfun lifecycle payload schema id component named inside the all
    # contract.
    "PUMPFUN_LIFECYCLE_PAYLOAD_SCHEMA_ID",
    "PUMPFUN_LIVE_NORMALIZER_PROFILE_ID",
    "PUMPFUN_MIGRATION_MINT_AMOUNT",
    "PUMPFUN_MIGRATION_STATE_PROFILE_ID",
    "PUMPFUN_POOL_MIGRATION_FEE",
    "PUMPFUN_PROTOCOL_NAME",
    "PUMPFUN_REAL_SOL_OFFSET",
    "PUMPFUN_REAL_TOKEN_OFFSET",
    "PUMPFUN_SNIPING_PROTOCOL_BUNDLE_ID",
    "PUMPFUN_STATIC_CURVE_STATE_PROFILE_ID",
    "PUMPFUN_TERMINAL_LIFECYCLE_PROFILE_ID",
    "PUMPFUN_TOKEN_2022_ATA_SCHEMA_ID",
    "PUMPFUN_TOKEN_2022_PROGRAM",
    "PUMPFUN_TOKEN_TOTAL_SUPPLY",
    "PUMPFUN_TRADE_PAYLOAD_SCHEMA_ID",
    "PUMPFUN_TRADE_SOL_SOURCE_ASSET",
    "PUMPFUN_UVA_SCHEMA_ID",
    "PUMP_BUY_EXACT_GROSS_SOL_FORMULA_V1",
    # Keep the pump buy legacy exact net sol formula v1 component named inside the all
    # contract.
    "PUMP_BUY_LEGACY_EXACT_NET_SOL_FORMULA_V1",
    "PUMP_HISTORICAL_COMPONENT_FEE_FORMULA_V1",
    "PUMP_SELL_EXACT_TOKEN_IN_FORMULA_V1",
    "PUMP_STATIC_PROGRAM_CONTRACT_V1",
    "SOLANA_SKIPPED_SLOT_SENTINEL_PROFILE_ID",
    "DerivedLifecycleGroupObservation",
    "ExcludedLaunchObservation",
    "PumpBuyQuote",
    "PumpCreatorFeeRoute",
    # Keep the pump curve lifecycle component named inside the all contract.
    "PumpCurveLifecycle",
    "PumpCurveStateV1",
    "PumpFeeBreakdown",
    "PumpFeeProfile",
    "PumpFeeRouting",
    # Keep the pump mode component named inside the all contract.
    "PumpMode",
    "PumpPrimitiveStateV1",
    "PumpProtocolFeeRoute",
    "PumpQuoteError",
    "PumpQuoteErrorCode",
    "PumpSellLiquidityPolicy",
    # Keep the pump sell quote component named inside the all contract.
    "PumpSellQuote",
    "PumpSlippageAssessment",
    "PumpTokenProgram",
    "PumpfunLiveNormalizationError",
    "PumpfunLiveNormalizationErrorCode",
    "PumpfunLiveNormalizer",
    "PumpfunNormalizationObservation",
    "PumpfunNormalizationObservationSink",
    "PumpfunNormalizationSession",
    "PumpfunNormalizationSummary",
    "PumpfunNormalizedBatch",
    "PumpfunProjectionError",
    "PumpfunProjectionErrorCode",
    # Keep the pumpfun projection spec component named inside the all contract.
    "PumpfunProjectionSpec",
    "PumpfunProtocolProjector",
    "PumpfunSnapshotValidator",
    "PumpfunSnipingProtocolRuntime",
    "SkippedSlotObservation",
    "assess_slippage",
    # Keep the buy quote component named inside the all contract.
    "buy_quote",
    "encode_launch_payload",
    "encode_lifecycle_payload",
    "encode_trade_payload",
    "historical_trade_fee_breakdown",
    "minimum_output_atomic",
    "pumpfun_account_requirements",
    # Keep the sell quote component named inside the all contract.
    "sell_quote",
]
