import { Component, lazy, Suspense, useEffect, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { HashRouter, Link, NavLink, Navigate, Outlet, Route, Routes, useLocation, useParams, useSearchParams } from 'react-router-dom';
import { QueryClientProvider, useQuery } from '@tanstack/react-query';
import { Activity, Menu, X } from 'lucide-react';
import { api, errorText, queryClient, type Schema } from '../api';
import { t, useLocale } from '../i18n';
import { SettingsMenu } from '../preferences';
import { Button, Card, Failure, Loading, PageTitle } from '../ui';
import { summary } from '../research/contracts';
import { ResearchMethod } from '../research/method';
import { demoClient } from './transport';
import type { DemoCatalog } from './client';
import '../styles.css';
import './style.css';
const ResearchResult=lazy(()=>import('../research/page').then(module=>({default:module.ResearchResult})));
const StrategyResults=lazy(()=>import('../results').then(module=>({default:module.StrategyResults})));
const LineageGraph=lazy(()=>import('../lineage').then(module=>({default:module.LineageGraph})));

function Layout(){useLocale();const [menu,setMenu]=useState(false),location=useLocation();useEffect(()=>{setMenu(false);window.scrollTo(0,0);},[location.pathname]);return <div className="app-shell"><a className="skip-link" href="#main" onClick={event=>{event.preventDefault();document.getElementById('main')?.focus();}}>{t('Skip to content')}</a><aside className={`sidebar ${menu?'is-open':''}`}><Link className="brand" to="/"><span><Activity size={24}/></span><div>onchain backtest engine<small>{t('INTERACTIVE DEMO')}</small></div></Link><nav aria-label={t('Main navigation')}><NavLink to="/" end>{t('Demo overview')}</NavLink><NavLink to="/research">{t('On-chain research')}</NavLink><NavLink to="/runs">{t('Strategy results')}</NavLink></nav><div className="sidebar-bottom"><SettingsMenu/><p>{t('Prepared examples · read only')}</p><p className="author-credit">{t('Made by')} <a href="https://github.com/happyer29" target="_blank" rel="noopener noreferrer">happyer29</a></p></div></aside><div className="main-shell"><header className="topbar"><Button className="menu-button" aria-label={t(menu?'Close menu':'Open menu')} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button><span>{t('Explore the interface with synthetic examples')}</span></header><div className="demo-banner" role="note"><strong>{t('Demo · test data')}</strong><span>{t('Calculated offline. No live wallets, source connection or new job execution.')}</span></div><main id="main" tabIndex={-1}><Boundary key={location.pathname}><Suspense fallback={<Loading/>}><Outlet/></Suspense></Boundary></main><footer className="app-footer">{t('Synthetic fixtures · no profitability claim')}</footer></div></div>}
class Boundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<Failure message={t('Could not render this screen. Reload the page to try again.')} retry={()=>window.location.reload()}/>:this.props.children}}
function useCatalog(){return useQuery({queryKey:['demo-catalog'],queryFn:()=>demoClient.catalog()})}
function Ready({children}:{children:(catalog:DemoCatalog)=>ReactNode}){const query=useCatalog();return query.isError?<Failure message={errorText(query.error)} retry={()=>void query.refetch()}/>:query.data?children(query.data):<Loading/>}
function RunCards({catalog}:{catalog:DemoCatalog}){return <div className="demo-cards">{catalog.runs.map(run=><Card key={run.id}><h2>{t(run.title)}</h2><p>{t(run.mode==='EXOGENOUS_REPLAY'?'Inspect an entry and exhausted sell attempts under observed reserves.':'Inspect a completed trade with explicitly synthetic sell funding.')}</p><Button asChild><Link to={`/runs/${run.id}`}>{t('Open test result')}</Link></Button></Card>)}</div>}
function Overview(){useLocale();return <Ready>{catalog=><><PageTitle eyebrow={t('Prepared examples')} title={t('Explore the demo')}/><p className="intro-text">{t('Inspect wallet connections and trace simulated trade outcomes. Every example uses generated test inputs, calculated by the project’s existing Python code.')}</p><Card><h2>{t('Wallet groups and shared purchases')}</h2><p>{t('{0} wallets · {1} pairs in the Non-Mayhem example',[catalog.wallets,catalog.research[0].counts.pairs])}</p><p>{t('Open groups, follow a wallet across groups, filter weaker links and inspect the purchases behind a pair.')}</p><Button asChild tone="primary"><Link to="/research">{t('Open wallet graph')}</Link></Button></Card><div className="section-intro"><h2>{t('Two execution outcomes')}</h2></div><RunCards catalog={catalog}/><Card><h3>{t('About the examples')}</h3><p>{t('The research fixture includes later repeat purchases, Mayhem tokens and missing creation data. Strategy examples show the same small Copy Buy scenario under two execution modes.')}</p><p>{t('Preparing data and running strategies require the local application. This site only displays exported results.')}</p></Card></>}</Ready>}
function Research(){useLocale();const [params,setParams]=useSearchParams();return <Ready>{catalog=><ResearchView key={params.get('artifact')??catalog.research[0].id} catalog={catalog} artifact={params.get('artifact')??catalog.research[0].id} select={id=>setParams({artifact:id})}/>}</Ready>}
function ResearchView({catalog,artifact,select}:{catalog:DemoCatalog;artifact:string;select:(id:string)=>void}){const allowed=[catalog.snapshot,...catalog.research.map(r=>r.id)].includes(artifact);const query=useQuery({queryKey:['research-summary',artifact],enabled:allowed,queryFn:({signal})=>summary(artifact,signal)});return <><PageTitle title={t('On-chain research')} eyebrow={t('Synthetic observations')}/><Card><label>{t('Prepared research example')}<select value={artifact} onChange={event=>select(event.target.value)}>{catalog.research.map(r=><option value={r.id} key={r.id}>{t(r.mode==='NON_MAYHEM'?'Without Mayhem':'All modes')}</option>)}<option value={catalog.snapshot}>{t('Source observations')}</option></select></label><p>{t('This selects a result calculated offline. Display filters below change only visible relationships.')}</p></Card><ResearchMethod/>{!allowed?<Failure message={t('This item is not included in the demo.')}/>:query.isError?<Failure message={errorText(query.error)} retry={()=>void query.refetch()}/>:query.data?<ResearchResult data={query.data} wholeGraph/>:<Loading/>}</>}
function Runs(){useLocale();return <Ready>{catalog=><><PageTitle title={t('Strategy results')} eyebrow={t('Prepared examples')}/><RunCards catalog={catalog}/></>}</Ready>}
function Run(){const {runId=''}=useParams();return <Ready>{catalog=>catalog.runs.some(run=>run.id===runId)?<StrategyResults key={runId} runId={runId} demo/>:<Failure message={t('This item is not included in the demo.')}/>}</Ready>}
function Provenance(){useLocale();const {artifactId=''}=useParams();const query=useQuery({queryKey:['demo-lineage',artifactId],queryFn:({signal})=>api<Schema<'ArtifactLineageResponse'>>(`/api/v1/lineage/${artifactId}`,{signal})});return <><PageTitle title={t('Offline provenance')} eyebrow={t('Synthetic fixtures')}/><p>{t('These IDs and dependencies were verified while preparing the test examples. The static site contains presentation exports, not executable artifact files.')}</p>{query.isError?<Failure message={errorText(query.error)} retry={()=>void query.refetch()}/>:query.data?<LineageGraph data={query.data}/>:<Loading/>}</>}
function Unavailable(){useLocale();return <Card><h1>{t('Unavailable in the demo')}</h1><p>{t('Preparing data and running strategies require the local application. This site only displays exported results.')}</p><Button asChild><Link to="/">{t('Back to overview')}</Link></Button></Card>}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={queryClient}><HashRouter><Routes><Route element={<Layout/>}><Route index element={<Overview/>}/><Route path="research" element={<Research/>}/><Route path="runs" element={<Runs/>}/><Route path="runs/:runId" element={<Run/>}/><Route path="artifacts/:artifactId" element={<Provenance/>}/><Route path="artifacts" element={<Navigate to="/" replace/>}/><Route path="*" element={<Unavailable/>}/></Route></Routes></HashRouter></QueryClientProvider>);
